### PR TITLE
[FIX] Auth code not being decoded properly

### LINKED ISSUE #835: Issue connecting to Google Drive from Buttercup desktop
Screen Shot 2019-10-29 at 10 49 06

As of this morning I have an issue connecting to Google Drive with the Desktop version of Buttercup? Not for an already existing archive, situated on Drive. That works okay. This happens when i want to add another archive. After clicking on 'Authenticate with Google' and going through the motions I get the error above. And of course the password etc. is correct. First I thought it was Manjaro related (since there is no official support for the AUR version), but it happens right now in Desktop on Mac also. Any ideas? thanks

### PR DESCRIPTION
**Pull request by riyadhalnur**
The auth code was being encoded 2 times causing an "invalid_grant"
error to be thrown. The fix is to decode the incoming auth token
first before the body object is stringified.

Screenshot from 2019-11-06 17-01-15

Fixes https://github.com/buttercup/buttercup-desktop/issues/835

### CODE REVIEW

**Review by perry-mitchell — APPROVED** [review]

**Comment by perry-mitchell** [comment]
This is excellent! We'll get this moving..

File: source/OAuth2Client.js [hunk 1]
```diff
@@ -46,8 +46,9 @@ export default class OAuth2Client extends EventEmitter {
     }
 
     async exchangeAuthCodeForToken(authCode) {
+        const decodedAuthCode = Object.keys(parse(authCode))[0];
```
Comment (perry-mitchell) [inline source/OAuth2Client.js]: Sorry, I must've skipped over this.. It's actually quite hard to read - Can we write this another way?

It looks as if you're parsing - getting an object - taking the keys and returning the first key?

**Review by perry-mitchell — CHANGES_REQUESTED** [review]
Confusing decode line..

File: source/OAuth2Client.js (hunk 1 above)
Comment (riyadhalnur) [reply source/OAuth2Client.js]: Yeah, it's a bit hard to read. Will update to be a non one-liner.

> It looks as if you're parsing - getting an object - taking the keys and returning the first key?

Correct.  The `parse` methods returns an object where the decoded value is the `key` sadly.

**Comment by riyadhalnur** [comment]
Used the low level `unescape`, exported from `querystring` stdlib, method for cleaner parsing

**Review by perry-mitchell — APPROVED** [review]
Great, thanks!

I might still consider finding a non-node alternative to the unescape method, but this does the trick for now.
